name: Qodana Documentation validation
on:
  pull_request:
    types: [opened, synchronize, reopened]
version: 1.0
jobs:
  qodana-check:
    name: Qodana Docs
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:

      - name: Fetch Sources
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}

      - name: Fetch Sources
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}

      - name: Download AsciiDoc plugin for AsciiDoc checks
        run: |
          curl -L -o asciidoctor-intellij-plugin.zip https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/download/0.43.6/asciidoctor-intellij-plugin-0.43.6.zip
          unzip asciidoctor-intellij-plugin.zip

      - name: Get two more commits so Qodana can identify the changes
        if: github.event_name == 'pull_request'
        run: git fetch --deepen=2

      - name: 'Qodana for Docs'
        uses: JetBrains/qodana-action@v2024.3.4
        with:
          upload-result: true
          args: >
            --linter,jetbrains/qodana-jvm-community:2024.3,
            -v,${{ github.workspace }}/asciidoctor-intellij-plugin:/opt/idea/plugins/asciidoctor-intellij-plugin,
            --baseline,doc/qodana-baseline.sarif.json

      # https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#example-workflow-that-runs-the-eslint-analysis-tool
      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: qodana-report
          path: qodana-report

  deploy-report:
    needs: qodana-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages-qodana
          fetch-depth: 0

      - name: Download Qodana Report
        uses: actions/download-artifact@v4
        with:
          name: qodana-report
          path: qodana-report

      - name: Move Report to PR Directory
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          mkdir -p reports/pr-$PR_NUMBER
          mv qodana-report/* reports/pr-$PR_NUMBER/

      - name: Commit and Push Report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add reports/
          git commit -m "Update Qodana report for PR #${{ github.event.pull_request.number }}" || exit 0
          git push origin gh-pages-qodana
