name: Qodana Code Quality Report

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write  # Needed to push reports to GitHub Pages
  pages: write
  actions: read

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.3
        with:
          args: --save-report

      - name: Upload Qodana Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: qodana-report
          path: qodana/report

